version: '3'
services:
  db:
    container_name: ldv-db
    image: mdillon/postgis
    volumes:
      - postgisPostgresql_ldv:/var/lib/postgresql/data
    env_file: 
      - ./.env_db
    ports:
      - "5432:5432"
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    container_name: ldv-api
    restart: always
    volumes:
      - /usr/src/api/node_modules
      - ./api/:/usr/src/api
    ports:
      - "7777:7777"
      - "9229:9229"
    command:
      "npm run debug"
    env_file: 
      - ./.env
    environment:
      - DUMMY=0
    depends_on:
      - db
  nginx:
    image: nginx:1.13
    container_name: ldv-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
    logging:
      driver: none
volumes:
  postgisPostgresql_ldv: