version: '3'
services:
  api:
    container_name: ldv-api
    image: TBA
    restart: always
    ports:
      - "7777:7777"
    command:
      "npm run start"
    env_file: 
      - /home/ec2-user/.env
    environment: 
      - NODE_ENV=production